name: Release new version to pypi.org

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: "ubuntu-latest"
    name: Release
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish binary wheel to releases
        uses: svenstaro/upload-release-action@2.4.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          asset_name: rki-covid-parser
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
